### ISSUE TITLE
Item code is broken

### ISSUE THREAD

**Issue by Khristian-kun** [SmartDEVTeam/SAO-MashUp-Addon#1]
The creative tab adds a new void item, also item doesnt exist!
![screenshot_2016-02-13-13-16-03](https://cloud.githubusercontent.com/assets/14143145/13027766/103f0098-d254-11e5-8746-c5c701572cc5.png)

**Comment by ISAAC300** [comment]
Drop in my account 2Million dollars per second , ad i help your project :), jk :v
drop the source in my twitter dm
@Lsaac300 :) is a true

**Comment by ThePixelGamer** [comment]
This has been fixed so I'm closing this issue

**Comment by Khristian-kun** [comment]
true lol
